# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coments',
            new_name='Comment',
        ),
    ]
